site_name: lazycogs
site_url: https://hrodmn.github.io/lazycogs/
site_description: Lazy, cloud-native raster mosaics powered by STAC.
repo_url: https://github.com/hrodmn/lazycogs
repo_name: hrodmn/lazycogs

theme:
  name: material
  logo: lazycogs-white.svg
  favicon: favicon.svg
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - search.suggest

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Examples:
    - demo.ipynb
    - hls.ipynb
  - Architecture: architecture.md
  - lazycogs vs odc-stac: lazycogs-odc-stac.ipynb
  - Contributing: CONTRIBUTING.md
  - API Reference:
    - Open: api/open.md
    - Mosaic Methods: api/mosaic.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            line_length: 80
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_toc: true
            signature_crossrefs: true
  - mkdocs-jupyter:
      execute: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - toc:
      permalink: true
