name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-python:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Ensure docs build without warnings
      - name: Check docs
        run: uv run --group docs mkdocs build --strict

      - name: Check slides
        run: quarto render slides/lightning-talk/index.qmd --to revealjs --output-dir /tmp/lazycogs-lightning-talk

      # Use ruff-action so we get annotations in the Github UI
      - uses: astral-sh/ruff-action@v3

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Run pre-commit
        if: matrix.python-version == '3.14'
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest
